### PR TITLE
feat: add set and clear token methods

### PR DESCRIPTION
**Pull request by IsraelOrtuno**
Added `getToken` and `clearToken` to local provider useAuthState composable for convenience. It's quite common to have cases where you have to "log in" the user manually when using this provider like when using social authentication, impersonation from a back-office or a custom register process. This PR just adds a couple of methods to make setting the cookie token more convenient and obvious.

Checklist:
- [X] issue number linked above after pound
- [ ] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [ ] attached screenshots / screenshot not applicable

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @IsraelOrtuno 👋 

Thank you for your contribution! I think it would be super helpful to create a quick note on this feature in the docs, to explain how to use this improvement. I think it would be good to write a quick section under `docs/nuxt-auth/0.6/resources`.

**Comment by IsraelOrtuno** [comment]
> Hi @IsraelOrtuno 👋
> 
> Thank you for your contribution! I think it would be super helpful to create a quick note on this feature in the docs, to explain how to use this improvement. I think it would be good to write a quick section under `docs/nuxt-auth/0.6/resources`.

Yes I thought so too but wasn't sure where to add it. I have updated the PR with a dedicated docs section which I guess it can be rearranged in the future 👍

**Comment by zoey-kaiser** [comment]
Thanks for adding the docs! I think the texts are good and well written, however after some more thinking, I would place them at the bottom of [this file](https://github.com/sidebase/nuxt-auth/blob/main/docs/content/v0.6/3.application-side/2.session-access-and-management.md) with a new heading, called `useAuthState() Composable`. You could then also mention that this section is meant for use with the local provider. 

Another thing I wanted to point out, AFAIK `useAuthState` is used by both the local and authjs providers, does including this feature break anything or interact with the Authjs provider? If you have not had the chance to test this yet, I can also do it today!

**Comment by IsraelOrtuno** [comment]
I don't think it has anything to do with `authjs` nor breaking anything. This is a `local` provider which is likely to be used with custom backend solutions.

I have also updated the docs with a more extensive information about what `useAuthState` composable does not only for `local` but for `authjs` too 👍

**Review by zoey-kaiser — APPROVED** [review]
Thank you so much for your contribution. I will merge this now, wait till I close issue #553 and then move on to releasing this in `0.6.0-rc.1`!

**Pull request merged**
