### PR TITLE
feat(#673, #523, #848): back-port authjs migration

### PR DESCRIPTION
**Pull request by phoenix-ru**
### 🔗 Linked issue

Relates to #673, #523, #848

This is a (partial) back-port of #818 to current code. Because completely updating to `@auth/core` makes the module very unstable, we decided to instead back-port the advancements made in the PR to also prepare for a future update.

Differences with #818 :
- no `@auth/core` version bump;
- internal helpers are preserved because they seem to work better than these of `@auth/core`;
- no breaking changes.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by zoey-kaiser — CHANGES_REQUESTED** [review]
- [ ] When I started the playground I got the following warning spammed in the console (c1). Note: This only occurs when a unauthenticated user visits the site


C1:
```
 WARN  [nuxt] useAsyncData must return a value (it should not be undefined) or the request may be duplicated on the client side.
```

**Comment by phoenix-ru** [comment]
> When I started the playground I got the following warning spammed 

This is likely related to dependencies. I will run an additional update cycle and see if that resolves the problem for you

**Comment by phoenix-ru** [comment]
Documented the issue here (tldr; it is not caused by us):
https://github.com/nuxt/nuxt/issues/28096#issuecomment-2291100566

**Review by zoey-kaiser — APPROVED** [review]
Thanks for the investigation! The workaround does remove the warning message. I see no reason to move forward with merging this PR. 

However, let's discuss how this PR integrates into our planned migration to authjs and what the next steps are prior to merging 😊

**Pull request merged**
