### PR TITLE
Feature/adding refresh token body key to refresh provider

### PR DESCRIPTION
**Pull request by hdood**
### 🔗 Linked issue

#689

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add `requestbodyKey`  to `module.ts` which will allow us to change refresh token body key in refresh request. 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @hdood 👋 

Thank you for your contribution. Please resolve the merge conflicts and then we should be able to review your PR this week 🤗

**Comment by hdood** [comment]
Hi @zoey-kaiser 

I've resolved the merge conflicts, this is my second PR so if there any other error please let me know and i will fix it right away.

**Comment by zoey-kaiser** [comment]
Hi @hdood,

Please check that the tests are passing! Then we can begin with a proper review 🤗

**Comment by zoey-kaiser** [comment]
Hi @hdood 👋 

We have opened a new PR (#727) with this change, as this PR has gotten Stale. Thank you for your contribution!

**Pull request closed without merging**
