### PR TITLE
fix: properly disable `getSession` endpoint for local and refresh

### PR DESCRIPTION
**Pull request by Armillus**
### 🔗 Linked issue

https://github.com/sidebase/nuxt-auth/issues/761

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The linked issue just covered half of the problem ; in the current form, `getSession` cannot be disabled, even with a configuration extracted [from the documentation](https://sidebase.io/nuxt-auth/getting-started/quick-start#provider-local) such as:

```js
{
  auth: {
    baseURL: '/api/auth',
    provider: {
      type: 'local',
      endpoints: {
        getSession: false,
      }
    }
  }
}
```

It's not an issue while you're not calling it, except that it is called by [`signIn` anyways](https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/src/runtime/composables/local/useAuth.ts#L35), at least with the `local` and `refresh` providers. Eventually, it means that an unexpected HTTP request is sent, which on one hand is inefficient, and on the other hand throws an exception from `signIn`, thus making it fail.

To fix those problems, this PR is applying the same strategy for `getSession` as for `signOut`, in both the function implementation and the exported type.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @Armillus 👋 

Firstly, I love the PR title 😆. Thank you for pushing this change, and I apologize for the short delay. I will do a review of this PR today 🤗

**Comment by Armillus** [comment]
Hi @zoey-kaiser,

I'm glad you liked the title 😄 No problem regarding the delay!
The prepack issue should be fixed now.

**Comment by zoey-kaiser** [comment]
>  The prepack issue should be fixed now.

They are indeed! Thank you so much! There is one small linting issue and otherwise I think we are good to go. Once we get this PR through, I will release a first RC of 0.8.0!

**Comment by Armillus** [comment]
Wonderful! I fixed the linting as well, sorry for the slight inconvenience.

**Review by zoey-kaiser — APPROVED** [review]

**Comment by zoey-kaiser** [comment]
Hi @Armillus 👋 

After testing this PR in 0.8.0, we decided to revert it. You can find a full explanation here: https://github.com/sidebase/nuxt-auth/issues/781#issuecomment-2209074510

**Pull request merged**
