### PR TITLE
feature: add possibility to disable signOut endpoint for local provider

### LINKED ISSUE #555: Add possibility to disable signOut endpoint
### Describe the feature

It would be nice if it would be possible to disable signOut endpoint for local provider. In our application it is enough to do sign out on the frontend part without making a backend call. Currently this is not possible as it throws error if no proper endpoint provided. In @nuxtjs/auth-next that was done by setting endpoint to false:
Screenshot 2023-10-23 at 14 14 16

Would it be possible to add this?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by anjarupnik**
Closes #555 .

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] manually checked my feature / checking not applicable
- [x] wrote tests / testing not applicable
- [x] attached screenshots / screenshot not applicable

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @anjarupnik 👋 

Thanks for the contribution! Could you please fix any merge conflicts? Then I can run the CI and do a review!

**Comment by anjarupnik** [comment]
Hi @zoey-kaiser, 
I am sorry, I forgot to pull the latest changes. Conflicts are resolved now.

**Review by zoey-kaiser — APPROVED** [review]

**Comment by zoey-kaiser** [comment]
Hi @anjarupnik 

I just merged and released `0.6.1`. You can install the new version and disable the signout api call 🥳 

https://github.com/sidebase/nuxt-auth/releases/tag/0.6.1

**Comment by anjarupnik** [comment]
@zoey-kaiser top, thank you! 😄

**Pull request merged**
