### PR TITLE
fix: middleware, status was always 'loading', if no session was set

### LINKED ISSUE #365: v0.6.0-beta.0 - Infinite redirect in navigation guard
### Environment

Nuxi 3.4.3                                                                                                                                                                     11:11:33 PM
                                                                                                                                                                               11:11:34 PM
RootDir: /Users/okaufmann/Code/nuxt/testproject                                                                                                             11:11:34 PM
Nuxt project info: (copied to clipboard)                                                                                                                                       11:11:34 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      nitro, app, runtimeConfig, tailwindcss, components, modules, auth, devtools, formkit, postcss, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.7, @vueuse/nuxt@10.1.2, @sidebase/nuxt-auth@0.6.0-beta.0, @formkit/nuxt@0.16.5, nuxt-graphql-client@0.2.27, @pinia/nuxt@0.4.9, @nuxt/devtools@0.4.5
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                    11:11:34 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

Setup nuxt-auth (v0.6.0-beta.0) and use the following config (local provider):

👉 nuxt.config.ts

```typescript
auth: {
    // Full url at which the app will run combined with the path to authentication.
    baseURL: `${process.env.API_URL}/api/auth`,

    // Configuration of the authentication provider.
    provider: {
      type: 'local',

      endpoints: {
        getSession: { path: '/user', method: 'get' },
      },
    },

    session: {
      // Whether to refresh the session every time the browser window is refocused.
      enableRefreshOnWindowFocus: true,

      // Whether to refresh the session every `X` milliseconds. Set this to `false` to turn it off. The session will only be refreshed if a session already exists.
      enableRefreshPeriodically: 5000,
    },

    // Whether to add a global authentication middleware that will protect all pages without exclusion
    globalAppMiddleware: {
      isEnabled: true,
    },
  },
```

Add site specific config on your login page:

👉 login.vue

```
definePageMeta({
  auth: {
    unauthenticatedOnly: true,
    navigateAuthenticatedTo: '/',
  },
})

```

### Describe the bug

It redirects infinetily to /login route. 

### Additional context

Appears since v0.6.0-beta.0. v0.6.0-alpha.2 works...

### Logs

```shell
500
Infinite redirect in navigation guard

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ./node_modules/nuxt/dist/pages/runtime/plugins/router.js:159:9
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
at async contextCaller (./node_modules/nuxt/dist/app/nuxt.js:62:9)
at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:31:7)
at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
at async ./.nuxt/dev/index.mjs:753:21
at async ./.nuxt/dev/index.mjs:395:22
```

### PR DESCRIPTION
**Pull request by Danielwinkelmann**
Closes #365 .

Checklist:
- [x] issue number linked above after pound (`#`)
- [x] manually checked my feature (playground)
- [x] testing not applicable (playground)
- [x] screenshot not applicable

### CODE REVIEW

**Comment by BracketJohn** [comment]
Great catch!

Could you briefly explain why this resolves #365, just so that we have the connection between this fix abd the issue? (: 

Thanks already and have a sunny sunday 🌞

**Comment by Danielwinkelmann** [comment]
@BracketJohn I tried to reproduce the error, add the login page and middleware to the playground and notice, that I can't trigger the middleware.
I found the loading bug and after this everything works fine.
So I can't reproduce the error from #365

**Comment by BracketJohn** [comment]
> So I can't reproduce the error from https://github.com/sidebase/nuxt-auth/issues/365

just to be clear: You mean with the changes of this PR the problem of #365 is gone? Makes sense!

**Review by BracketJohn — APPROVED** [review]

**Comment by BracketJohn** [comment]
Thanks @Danielwinkelmann 🤝

**Comment by minhphuc429** [comment]
@Danielwinkelmann
Thanks, You made my day.

**Pull request merged**
