### PR TITLE
docs: added Laravel passport SSO example

### LINKED ISSUE #149: How to use it with Laravel Passport ?
### Ask your question

I need to integrate it with Laravel Passport (password grant type) like the older version of nuxt auth because i want to use it in the first-party app workflow. How to do this ? Should i use credentials or oauth ?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jericho1060**
Closes #149 (already closed).

It's an update of the documentation for Laravel Passport asked by @zoey-kaiser 

Content tested and working using Laravel 9 and Laravel 10.

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @Jericho1060 👋 

Thanks for writing the guide. I think it will be super helpful! Ill get around to a review later today, however I already noticed two small things.

- There are a lot of blank lines at the bottom of the file, can you reduce it to 1?
- Do you want to add a note back to https://github.com/sidebase/nuxt-auth/issues/149, so people could follow the discussion we had? You are also welcome to add a small credit to yourself at the bottom, as you came up with this solution!

**Comment by Jericho1060** [comment]
humm it seems github removed the empty line at the end ...

but i have one in my IDE 
image

**Comment by zoey-kaiser** [comment]
> humm it seems github removed the empty line at the end ...

It has not. Github by default not does show the last empty line (to preserve space IG), but instead has a little icon it there is no new line at the end. It looks good now! Thanks!

**Review by zoey-kaiser — APPROVED** [review]

**Comment by Jericho1060** [comment]
Thank you @zoey-kaiser sorry for my english, this is not my native language :D

**Comment by zoey-kaiser** [comment]
> Thank you @zoey-kaiser sorry for my english, this is not my native language :D

No need to apologize at all! You did a really good job. Thank you so much for your contribution 😊

**Pull request merged**
