### PR TITLE
Docs: Fix broken glossary links

### PR DESCRIPTION
**Pull request by pascalwengerter**
Figured I'd open a PR instead of an issue. See commits&changes, minor update to docs/urls.

Checklist:
- [x] manually checked my feature / checking not applicable (checking not possible, `npx nuxi init docs -t nuxt-themes/docus-starter` fails)
- [x] screenshot not applicable

### CODE REVIEW

**Review by BracketJohn — CHANGES_REQUESTED** [review]
thanks you so much ❤️ 

Please revert the changes made to the package-lock and we are good to go!

**Comment by pascalwengerter** [comment]
> thanks you so much ❤️
> 
> Please revert the changes made to the package-lock and we are good to go!

@BracketJohn done, and rebased (I guess that's why you merged main into my branch originally)? I thought I'd do the project a solid by running `npm audit fix` (since there were warnings upon setting it up locally), which ofc produced the diff in the package-lock

**Review by BracketJohn — APPROVED** [review]

**Comment by BracketJohn** [comment]
> @BracketJohn done, and rebased (I guess that's why you merged main into my branch originally)? 

yup, thanks!

> I thought I'd do the project a solid by running npm audit fix (since there were warnings upon setting it up locally), which ofc produced the diff in the package-lock

very good thinking ❤️  However, as this is a security-related project we want to make concious, reviewed changes to the package-lock (even if it comes from `npm audit fix`). That is why I want this one just for doc-fixes - hope that makes sense (:

**Comment by pascalwengerter** [comment]
> > @BracketJohn done, and rebased (I guess that's why you merged main into my branch originally)?
> 
> yup, thanks!
> 
> > I thought I'd do the project a solid by running npm audit fix (since there were warnings upon setting it up locally), which ofc produced the diff in the package-lock
> 
> very good thinking ❤️ However, as this is a security-related project we want to make concious, reviewed changes to the package-lock (even if it comes from `npm audit fix`). That is why I want this one just for doc-fixes - hope that makes sense (:

Sure thing, thanks for the swift reactions!

**Pull request merged**
