### PR TITLE
Bump dependencies and add `ModuleOptionsNormalized` type

### LINKED ISSUE #660: Remove VueUse dependency if it's not necessary
### Describe the feature

Currently, this project includes VueUse as a dependency. However, no file seems to use VueUse features in the codebase. 

The dependency was introduced in this https://github.com/sidebase/nuxt-auth/pull/317, but I was not clear where and why it used VueUse.

So, I was wondering if this project still needs VueUse or not. If not, it should be removed from package.json since it affects the project's dependencies that depend on this project.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phoenix-ru**
Addresses known security advisories. Strengthens the type safety of the module.

Closes #660

### CODE REVIEW

**Comment by codetheorist** [comment]
I've closed my PR but to be fair, that one could be merged straight away and your PR could be merged later with no issues. No reason to do such a thing, especially as when people take the time out to contribute to projects with both issues and code they aren't even rewarded with the benefit of being labelled as a contributor to said project, because somebody else decided to open a PR, add their changes and disregard the contributors work. There is absolutely no need for this whatsoever and is a main issue with open source. If contributors don't get recognised because someone decides "I'll close that PR, it's too simple" or "We'll squash the history so the contributors don't show up in commit history" or any other farce then they are going to be less likely to want to contribute to ANY open source projects, not just your own. Luckily I'm not that petty and will continue to contribute to open source projects, just maybe not this one.

**Comment by codetheorist** [comment]
So you wasted your own time adding the 660 changes to your PR when you could have merged mine and had me labelled as a contributor, seeing as though a create issues, comment on issues and do TRY to fix issues.

**Comment by codetheorist** [comment]
I've closed that PR anyway, I won't waste my own time in future.

**Comment by codetheorist** [comment]
> Approved, however let's make a pre-release and verify the changes work in the nuxt-auth-example!

Would it be worth reopening my original OR for the VueUse issue? It seems beneficial and is a very minimal PR with minimal testing required so could be merged quite quickly.

**Comment by phoenix-ru** [comment]
@codetheorist I see your point. However, I want to push a more general dependency revamp so that it unlocks the other PRs.
We have some breaking changes planned for 0.7 and therefore we need to make 0.6 as stable as possible, which also includes adding E2E tests.

There's nothing wrong with your PR.

**Comment by codetheorist** [comment]
That in no way stated why my PR couldn't be merged and also didn't negate the fact that I'd already done the work, if even only 15 minutes (including searching for installs, update lock files), which was rendered pointless as you decided to do it again after seeing my already open PR.

**Comment by codetheorist** [comment]
It's done now anyway but I'll be more reluctant to devote my time to issues and PRs within this repository moving forward.  When people try to contribute, the least you can do is let them get the "contributor" badge to acknowledge them as such.

**Comment by zoey-kaiser** [comment]
> That in no way stated why my PR couldn't be merged and also didn't negate the fact that I'd already done the work, if even only 15 minutes (including searching for installs, update lock files), which was rendered pointless as you decided to do it again after seeing my already open PR.

Hi @codetheorist 👋 
Sorry for not merging or prioritizing your PR. We are very thankful for your contribution and the only reasons why we decided not to merge your PR was:
- This PR also changed a lot of packages, which greatly changed the `pnpm-lock.json`. Resolving merge conflicts within this file is normally very tedious and did not make a lot of sense, when we have two PRs open for this propose.
- removing the `vue-use` package is not blocking anyone from continuing to use `NuxtAuth`. I agree that we should definitely remove dead-code, but I see no reasons to prioritize it so far, that we merge it prior to breaking changes and make a dedicated release for it.

> It's done now anyway but I'll be more reluctant to devote my time to issues and PRs within this repository moving forward. When people try to contribute, the least you can do is let them get the "contributor" badge to acknowledge them as such.

I think it is great that you are trying to contribute to open source projects, however I think that you also need to see this from our perspective. Our main goal is to continue developing NuxtAuth and we really appreciate help from outside contributors, however, if mergeing other PRs causes more work for us, then it is not worth it. I would also want to point out that this moment, that this PR was already opened, before you created your PR (taken, it did not include removing `vue-use`), but IMO it makes a lot more sense to bundle bigger adjustments to packages, due to the reasons mentioned above.
We could have announced this earlier, but I would still like to ask you to respect our technical decisions and internal project management, if we decide to tackle issues through PRs from our core developers.

I would recommend discussing and pinging us in issues, before beginning to work on them. This way we can better coordinate with you, to ensure excess work is not done.

**Pull request merged**
