### PR TITLE
feat: added cookie provider

### LINKED ISSUE #494: Add Provider: Cookie
### Describe the feature

A lot of systems are cookie/session based auth, and are unwilling to migrate to JWT based auth.

As with the nuxt2 version of auth-nuxt, we should support cookie based authentication

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shainegordon**
Closes #494 .

Checklist:
- [X] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [X] manually checked my feature / checking not applicable
- [X] wrote tests / testing not applicable
- [X] attached screenshots / screenshot not applicable

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Wow! This is a huge contribution! Thank you @shainegordon! ❤️ 

Ill approve the workflow and have our CI do an initial runthrough. Once the CI is satisfied I will pass this along for a proper review and we can then look to merge it!

**Comment by shainegordon** [comment]
I see the CI failed.

Unfortunately I will only be able to look at this after the 12th August, as
I just went on holiday and don’t have access to my development environment.

I swear that I looked for a test folder, and didn’t see any, obviously I
was going mad 😅

**Comment by zoey-kaiser** [comment]
> Unfortunately I will only be able to look at this after the 12th August, as

Not a problem at all! Ping me once your back and I can relook at it!

> I swear that I looked for a test folder, and didn’t see any, obviously I

We use the playground as our test environment. Both playgrounds are started and it checks if any issues occur! But in your PR its only a simple linting issue!

**Comment by shainegordon** [comment]
@zoey-kaiser I have gone ahead and fixed the linting issues.

I've also added a GitHub Action job "test-playground-cookie" to align with the others

**Comment by zoey-kaiser** [comment]
> @zoey-kaiser I have gone ahead and fixed the linting issues.

Perfect! I am letting the CI run once again and if everything goes well, I will do some testing! We also need some documentation to the new provider, do you feel comfortable adding it in `/docs`?

**Comment by shainegordon** [comment]
> > @zoey-kaiser I have gone ahead and fixed the linting issues.
> 
> Perfect! I am letting the CI run once again and if everything goes well, I will do some testing! We also need some documentation to the new provider, do you feel comfortable adding it in `/docs`?

Sure, I will see if I can update the docs sometime this week.

I just got back from leave, so have a bit of catching up to do for the day job :)

**Comment by yabe-diverta** [comment]
any updates?

**Comment by AlejandroAkbal** [comment]
EAGERLY awaiting this to be merged

**Comment by zoey-kaiser** [comment]
Hi everyone!

I want to merge this and begin testing it as soon as we release `0.6.0`! I don't want to cram this into that release, as we have already done a lot of testing on it and introducing this, may break some things. 
I hope we can release 0.6.0 next week and then I can do a new beta release with this provider!

Hang tight. I have not forgotten about you ♥️

**Comment by benjipott** [comment]
Hi all, i added options to local provider to prevent adding many provider workflows. you can see all here.
IMHO, it's better to add simple options to the config file.
https://github.com/sidebase/nuxt-auth/pull/564

**Comment by zoey-kaiser** [comment]
Closed in favour of #588

**Pull request closed without merging**
