### PR TITLE
feat: implement refresh provider schema

### PR DESCRIPTION
**Pull request by dommi10**
this pull request is based on  #373 with all bugs fixed and suggestion

Closes # .

Checklist:
- [ ] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [ ] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [ ] attached screenshots / screenshot not applicable

### CODE REVIEW

**Review by zoey-kaiser — COMMENTED** [review]
What I saw after a quick flyover is that there were no changes to the documentation. This would be needed before a release. 

Do you feel like you could write these? Otherwise you can also ignore it for now and ill write some docs, while doing a functional review!

**Comment by clcoco** [comment]
Is there an ETA as to when the new documentation will be released?

**Comment by dommi10** [comment]
> What I saw after a quick flyover is that there were no changes to the documentation. This would be needed before a release. 
> 
> 
> 
> Do you feel like you could write these? Otherwise you can also ignore it for now and ill write some docs, while doing a functional review!

I prefer ignore from now 😂😂 
If things work as expected then we can think how to do that


Still waiting for a beta release another name this week as expected  
@Zoey

**Comment by zoey-kaiser** [comment]
Published alpha version can be found here https://www.npmjs.com/package/@dommidev10/nuxt-auth, thanks to @dommi10 ❤️

**Comment by zoey-kaiser** [comment]
Hi @dommi10, could you please fix the lint issues? Then I will go ahead and review this!

**Comment by dommi10** [comment]
> Hi @dommi10, could you please fix the lint issues? Then I will go ahead and review this!

Sure, I will do it tomorrow

**Comment by dommi10** [comment]
> Hi @dommi10, could you please fix the lint issues? Then I will go ahead and review this!

hi @zoey-kaiser, i finished with lint fix

**Comment by dommi10** [comment]
Thanks you @zoey-kaiser 
I can't wait😇

**Comment by zoey-kaiser** [comment]
Alpha version released! You can find the release notes here:

https://github.com/sidebase/nuxt-auth/releases/tag/0.6.3-alpha.1

**Comment by dommi10** [comment]
Thank you @zoey-kaiser for your dedicated time and suggestions

**Pull request merged**
