### PR TITLE
fix: Improve typing of sessiondata

### PR DESCRIPTION
**Pull request by Danielwinkelmann**
Closes TODO: Improve typing of sessiondata.

Checklist:
- [x] manually checked my feature
- [x] testing not applicable
- [x] attached screenshots

config_with_session_data
CleanShot 2023-05-10 at 13 15 46@2x

### CODE REVIEW

**Review by BracketJohn — COMMENTED** [review]
Could you add some documentation for this as well?

You can do so inside the `v0.6` folder of the docs (: 

Thanks for the (many) contributions, you are awesome 💯 ❤️

**Comment by Danielwinkelmann** [comment]
id add an example with an array type: 
`sessionDataType: { id: 'string', email: 'string', name: 'string', role: 'admin | guest | account', subscriptions: "{ id: number, status: 'ACTIVE' | 'INACTIVE' }[]" }`

will result in: 
session_data_interface

**Comment by BracketJohn** [comment]
This is great stuff (: 

Merging now - will do a release soon 🎊 

Your contributions are just great, are you on our discord by any chance? Would love to give you a special status there.

**Comment by Danielwinkelmann** [comment]
Hi, Im on Discord, but not very often. I send u a friend request. Hunter1989

**Comment by BracketJohn** [comment]
No worries - I just added you ❤️ Let me know if there's a better way to connect there, I'm also open for old school stuff like e-mail :D

**Pull request merged**
