### PR TITLE
fix: addDefaultCallback can be set with refresh and local providers

### PR DESCRIPTION
**Pull request by nojiritakeshi**
### 🔗 Linked issue
https://github.com/sidebase/nuxt-auth/issues/622
https://github.com/sidebase/nuxt-auth/issues/656

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
addDefaultCallback can now be set by refresh and local provider.
I have confirmed that it works in playground.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @nojiritakeshi 👋 

Thank you for your contribution, and I apologize for the delay! As this change is very straight forward and reuses logic from the AuthJS provider, I think we can quickly push this through and release it in 0.8.0! 

Could you please fix the merge conflicts and then we can do a review and hopefully merge without any issues 😊

**Comment by nojiritakeshi** [comment]
Hi @zoey-kaiser !
Thanks for the review.
Conflicts have been resolved, please check again.

**Review by zoey-kaiser — CHANGES_REQUESTED** [review]
Hi @nojiritakeshi 👋 
Sorry for the delay in the review, I have been pretty swamped lately 😓 

Thanks for the awsome PR! Could you please look into making this new option configurable via the nuxt config, like with the authjs provider?

There we allow you to set `addDefaultCallbackUrl` to a boolean to enable / disable automatic callback URL detection or hard code it to a string, which is then always the callback URL? 

I think this would allow for more flexibility and would also match the other providers! Thank you so much 😊

**Comment by nojiritakeshi** [comment]
Hi @zoey-kaiser 😄 

Indeed. I agree with that opinion.
I may take some time since I've been busy lately, but I'll try to find the time to fix it.

**Comment by nojiritakeshi** [comment]
Hi @zoey-kaiser .
This modification is made so that the string set in the addDefaultCallback property in nuxt.config is applied to the callbackUrl.

> There we allow you to set addDefaultCallbackUrl to a boolean to enable / disable automatic callback URL detection or hard code it to a string, which is then always the callback URL?

Therefore, I do not see the need to make a new correction to this point, do you?

Please let me know if I am misguided!

**Review by zoey-kaiser — APPROVED** [review]

**Comment by zoey-kaiser** [comment]
>  This modification is made so that the string set in the addDefaultCallback property in nuxt.config is applied to the callbackUrl.

You are right! I revised this PR and agree! Sorry about the confusion! Thank you for your contribution! I will release this PR in `0.8.0-rc.1` now! 🥳

**Pull request merged**
